
import './style.css' // CSS
import 'scalajs:main.js' // main.js: generated by sbt fastLinkJS
// replaced to: import "/target/scala-3.7.3/livechart-fastopt/main.js?t=1763621083711"

// NEED TO re-export
export * from 'scalajs:main.js'
